version: '3'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    environment:
      - SE_OPTS=--no-sandbox
    shm_size: 2g
    ports:
      - "4444:4444"
  
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auction_crawler
    environment:
      - DOCKER_ENV=true
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - chrome
    command: python src/local.py

volumes:
  pgdata: